### ISSUE TITLE
Documentation to create a Pull Request.

### ISSUE THREAD

**Issue by vanlooverenkoen** [cdancy/bitbucket-rest#128]
I want to create a PR with your library. But I always get

```
com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/String;)Lcom/google/common/base/Objects$ToStringHelper;

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4151)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5140)
	at org.jclouds.reflect.Reflection2.get(Reflection2.java:345)
	at org.jclouds.reflect.Reflection2.method(Reflection2.java:132)
	at org.jclouds.reflect.Reflection2.method(Reflection2.java:112)
	at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:120)
	at com.sun.proxy.$Proxy49.pullRequestApi(Unknown Source)
	at com.icapps.build.gradle.plugin.tasks.bitbucket.BitbucketTest.testPr(BitbucketTest.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Objects.toStringHelper(Ljava/lang/String;)Lcom/google/common/base/Objects$ToStringHelper;
	at org.jclouds.reflect.Reflection2$TypeTokenNameAndParameterTypes.toString(Reflection2.java:300)
	at org.jclouds.reflect.Reflection2$7.load(Reflection2.java:273)
	at org.jclouds.reflect.Reflection2$7.load(Reflection2.java:256)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 31 more

```

This is the code used to trigger this exception.

```
        val repoName = "android_gradle_demo"
        val repoSlug = "android_gradle_demo"
        val project = "android_build"

        val client = BitbucketClient.builder()
                .endPoint("my-base-url")
                .token("my-token")
                .build()

        val currentBranch = "feature/bitbucket-integration"

        val prTitle = "Test From Gradle Plugin"
        val prDescription = "Description From Gradle Pugin"

        val branchToMerge = BitbucketPrTask.branchPrefix + currentBranch
        val branchMergeInto = BitbucketPrTask.branchPrefix + BitbucketPrTask.branchName

        val projKey = ProjectKey.create(project)
        val repo = MinimalRepository.create(repoSlug, null, projKey)

        val fromRef = Reference.create(branchToMerge, repo, branchToMerge)
        val toRef = Reference.create(null, repo)

        val pr = CreatePullRequest.create(prTitle, prDescription, fromRef, toRef, null, null)
        val result = client.api().pullRequestApi().create(project, repoName, pr)
```

I think I am doing something wrong but it is unclear how to build a simple createPullRequest request.

**Comment by cdancy** [comment]
Closing. Feel free to re-open if you have any questions.
